version: "3.1"
services: 
  backend: 
    image: node:14-alpine 
    container_name: billing_backend 
    working_dir: /app 
    restart: always 
    ports: 
      - 8001:8001 
    volumes:
      - ./server:/app 
    command: ['sh', '+x', './docker-entrypoint.sh'] 
  frontend: 
    image: node:14-alpine 
    container_name: billing_frontend 
    working_dir: /app 
    ports: 
      - 8000:8000 
    volumes: 
      - ./client:/app 
    command: ['sh', '+x', './docker-entrypoint.sh']
